In [1]:
import os
from tqdm import tqdm
import json
import gc
import numpy as np
import pandas as pd

pd.options.display.max_columns = 999

%load_ext autoreload
%autoreload 2

### Read Data

In [2]:
s3path = './3-Data_Sets-Analysis/3a-Analysis_Data_Sets/'
s3files = os.listdir(s3path)
print(s3files)

['cvdoutcomes.sas7bdat', 'mind.sas7bdat', 'bloodpressure.sas7bdat', 'accord_key.sas7bdat', 'microvascularoutcomes.sas7bdat', 'eye.sas7bdat', 'mind_mri.sas7bdat', 'activitystatus.sas7bdat', 'ecg.sas7bdat', 'lipids.sas7bdat', 'sae.sas7bdat', 'hypoglycemiatime1st.sas7bdat', 'hba1c.sas7bdat', 'otherlabs_ver2.sas7bdat', 'concomitantmeds.sas7bdat', 'hypoglycemiaevents.sas7bdat']

In [3]:
s4path = './4-Data_Sets-CRFs/4a-CRF_Data_Sets/'
s4files = os.listdir(s4path)
print(s4files)

['f29_champsphysicalactivity.sas7bdat', 'f01_inclusionexclusionsummary.sas7bdat', 'f22_costsubstudy.sas7bdat', 'f23_hrql.sas7bdat', 'f08_09_glycemiamanagement.sas7bdat', 'f26_dietquestionnaire.sas7bdat', 'f34_intervalhistoryfollowup.sas7bdat', 'f13_intensivebpmanagement.sas7bdat', 'f03_lipidtrialscreening.sas7bdat', 'f02_bptrialscreening.sas7bdat', 'f16_lipidmedicationsmanagement.sas7bdat', 'f19_healthutilitiesindex.sas7bdat', 'f14_standardbpmanagement.sas7bdat', 'f36_annualfollowupphysicalexam.sas7bdat', 'f10_glycemiamedicationslog.sas7bdat', 'f07_baselinehistoryphysicalexam.sas7bdat', 'f15_bptrialmedicationslog.sas7bdat', 'f49_standingbloodpressure.sas7bdat']

In [4]:
def read_data(path, files):
    output = {}
    for _file in tqdm(files, total=len(files)):
        output[_file] = pd.read_sas(path+os.sep+_file, 'sas7bdat')
    return output

In [5]:
s3data = read_data(s3path, s3files)
gc.collect()

100%|██████████| 16/16 [00:06<00:00,  2.36it/s]

91

In [6]:
s4data = read_data(s4path, s4files)
gc.collect()

100%|██████████| 18/18 [00:10<00:00,  1.09it/s]

420

In [7]:
s3data.keys()

dict_keys(['mind.sas7bdat', 'lipids.sas7bdat', 'concomitantmeds.sas7bdat', 'hypoglycemiaevents.sas7bdat', 'accord_key.sas7bdat', 'ecg.sas7bdat', 'sae.sas7bdat', 'cvdoutcomes.sas7bdat', 'otherlabs_ver2.sas7bdat', 'mind_mri.sas7bdat', 'hba1c.sas7bdat', 'hypoglycemiatime1st.sas7bdat', 'bloodpressure.sas7bdat', 'activitystatus.sas7bdat', 'microvascularoutcomes.sas7bdat', 'eye.sas7bdat'])

### Show sample cases

In [8]:
s3data['cvdoutcomes.sas7bdat'].sample(3)

,MaskID,censor_po,type_po,fuyrs_po,fuyrs_po7p,censor_tm,type_tm,fuyrs_tm,fuyrs_tm7p,censor_cm,fuyrs_cm,fuyrs_cm7p,censor_nmi,type_nmi,fuyrs_nmi,fuyrs_nmi7p,censor_nst,type_nst,fuyrs_nst,fuyrs_nst7p,censor_tst,fuyrs_tst,fuyrs_tst7p,censor_chf,fuyrs_chf,fuyrs_chf7p,censor_ex,type_ex,fuyrs_ex,fuyrs_ex7p,censor_maj,type_maj,fuyrs_maj,fuyrs_maj7p
8099,108100.0,0.0,b'Stroke',4.933738,NaN,1.0,NaN,6.164384,NaN,1.0,6.164384,NaN,1.0,NaN,6.164384,NaN,0.0,b'Stroke',4.933738,NaN,0.0,4.933738,NaN,1.0,6.164384,NaN,0.0,b'MI or Stroke',4.933738,NaN,1.0,NaN,6.164384,NaN
6836,106837.0,1.0,NaN,4.295711,NaN,1.0,NaN,4.295711,NaN,1.0,4.295711,NaN,1.0,NaN,4.295711,NaN,1.0,NaN,4.295711,NaN,1.0,4.295711,NaN,1.0,4.295711,NaN,0.0,b'Revasc',2.583382,NaN,1.0,NaN,4.295711,NaN
7959,107960.0,1.0,NaN,3.000846,NaN,0.0,b'Other Death',3.222764,NaN,1.0,3.222764,NaN,1.0,NaN,3.000846,NaN,1.0,NaN,3.000846,NaN,1.0,3.000846,NaN,1.0,3.000846,NaN,1.0,NaN,3.000846,NaN,1.0,NaN,3.000846,NaN

In [9]:
s3data['cvdoutcomes.sas7bdat']['censor_po'].value_counts() / s3data['cvdoutcomes.sas7bdat'].shape[0] * 100

1.0    89.796117
0.0    10.203883
Name: censor_po, dtype: float64

In [10]:
s4data['f07_baselinehistoryphysicalexam.sas7bdat'].describe()

,MaskID,livealon,edu,yrsdiab,yrslipi,yrstens,ulcer,protein,hartfail,neuropat,depressn,eyedisea,histhart,cigarett,smokelif,quityrs,alcohol,ins_cover,dk_unins,drugbene,wt_kg,ht_cm,waist_cm,scrright,scrleft,eyesurg,recat_yag,reret_vit,reothr,lecat_yag,leret_vit,leothr,retpathy,lrtpathy,rrtpathy,visloss,le_vloss,re_vloss,hfrswell,hfrswech,hfrshort,hfrshoch,hfrurine,hfrurich,chest_exam,famphis,fappear,fdeform,finfect,fdryski,ffissur,fother,fulcer,fankle,fvibrat,ffilam,MNSIscor,feeling
count,10251.000000,10249.000000,10244.000000,10159.000000,7165.000000,7726.000000,10250.000000,10250.000000,10250.000000,10250.000000,10249.000000,10250.000000,10250.000000,10251.000000,8919.000000,4564.000000,10246.000000,8787.0,1461.0,10248.000000,10249.000000,10247.000000,10150.000000,9802.000000,9797.000000,10219.000000,966.0,746.0,440.0,916.0,715.0,451.0,8969.000000,839.0,839.0,8937.000000,990.0,977.0,9073.000000,2407.000000,9073.000000,1077.000000,9072.000000,1706.000000,5560.000000,10126.00000,4642.0,541.0,222.0,3284.0,111.0,1787.0,10180.000000,10118.000000,10163.000000,10173.000000,10001.000000,10171.000000
mean,105126.000000,1.202751,2.698946,10.799587,5.956455,10.228061,1.955122,1.801463,1.951805,1.732976,1.763782,1.688390,2.252585,1.860599,1.482677,19.263585,0.955885,1.0,1.0,1.552010,93.512265,170.166195,106.726236,73.061620,73.154027,1.776103,1.0,1.0,1.0,1.0,1.0,1.0,1.882373,1.0,1.0,1.858789,1.0,1.0,1.712003,1.875364,1.871817,1.849582,1.789683,1.906213,1.956655,1.97857,1.0,1.0,1.0,1.0,1.0,1.0,0.017289,0.344436,0.234478,0.120368,2.117938,75.703569
std,2959.353139,0.402069,1.013506,7.595062,5.697380,9.587371,0.207046,0.398918,0.214189,0.442427,0.424778,0.463174,0.930561,0.346381,0.499728,12.334816,2.674502,0.0,0.0,1.021592,18.406564,9.796194,13.640202,15.300796,15.225314,0.416874,0.0,0.0,0.0,0.0,0.0,0.0,0.322184,0.0,0.0,0.348258,0.0,0.0,0.452855,0.330375,0.334311,0.357647,0.407557,0.291617,0.203652,0.14482,0.0,0.0,0.0,0.0,0.0,0.0,0.130352,0.439999,0.318250,0.253826,1.716104,16.400582
min,100001.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.0,1.0,1.000000,51.700000,144.800000,71.100000,0.000000,0.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000
25%,102563.500000,1.000000,2.000000,5.000000,2.000000,3.000000,2.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,9.000000,0.000000,1.0,1.0,1.000000,80.300003,162.600000,96.500000,69.000000,69.000000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0,2.000000,1.0,1.0,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.500000,70.000000
50%,105126.000000,1.000000,3.000000,10.000000,4.000000,7.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,1.000000,19.000000,0.000000,1.0,1.0,1.000000,92.500000,170.200000,106.700000,77.000000,77.000000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0,2.000000,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,2.000000,80.000000
75%,107688.500000,1.000000,4.000000,15.000000,8.000000,15.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,29.000000,0.000000,1.0,1.0,2.000000,105.700000,177.800000,116.000000,82.000000,83.000000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0,2.000000,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,1.000000,0.500000,0.000000,3.000000,90.000000
max,110251.000000,2.000000,4.000000,35.000000,29.000000,44.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,2.000000,2.000000,51.000000,20.000000,1.0,1.0,4.000000,145.100006,193.000000,143.500000,92.000000,92.000000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0,2.000000,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,6.000000,100.000000

### Create meta data - Pivot table

In [11]:
_s = s3data['bloodpressure.sas7bdat'].copy()

In [12]:
pivot_s = pd.pivot_table(_s, values='sbp', index='MaskID', columns='Visit', aggfunc='mean', fill_value=None, dropna=False)

In [13]:
pivot_s.head()

Visit,b'BLR',b'EXIT',b'F01',b'F02',b'F03',b'F04',b'F06',b'F08',b'F10',b'F12',b'F14',b'F16',b'F18',b'F20',b'F22',b'F24',b'F26',b'F28',b'F30',b'F32',b'F34',b'F36',b'F38',b'F40',b'F42',b'F44',b'F46',b'F48',b'F50',b'F52',b'F54',b'F56',b'F58',b'F60',b'F62',b'F64',b'F66',b'F68',b'F70',b'F72',b'F74',b'F76',b'F78',b'F80',b'F82',b'F84'
MaskID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001.0,127.0,108.0,140.0,133.0,126.0,117.0,130.0,121.0,NaN,125.0,NaN,123.0,NaN,124.0,NaN,118.0,NaN,117.0,125.0,121.0,111.0,115.0,120.0,109.0,118.0,115.0,115.0,114.0,127.0,119.0,111.0,119.0,110.0,102.0,116.0,100.0,106.0,110.0,116.0,110.0,119.0,116.0,119.0,110.0,117.0,110.0
100002.0,109.0,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.0,NaN,123.0,NaN,111.0,NaN,121.0,NaN,126.0,NaN,112.0,NaN,126.0,NaN,119.0,NaN,125.0,NaN,124.0,NaN,112.0,NaN,133.0,NaN,134.0,NaN,119.0,NaN,119.0,NaN,123.0,NaN,133.0,NaN,129.0,NaN,133.0
100003.0,143.0,NaN,NaN,NaN,NaN,146.0,NaN,NaN,NaN,125.0,NaN,152.0,NaN,NaN,NaN,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100004.0,114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,NaN,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100005.0,148.0,154.0,NaN,NaN,NaN,140.0,NaN,121.0,NaN,153.0,NaN,158.0,NaN,129.0,NaN,145.0,NaN,144.0,NaN,148.0,NaN,134.0,NaN,128.0,NaN,157.0,NaN,145.0,NaN,147.0,NaN,148.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
_s.sample(3)

         MaskID    Visit    sbp   dbp    hr
71051  103937.0  b'EXIT'  129.0  68.0  66.0
15810  100874.0   b'F36'  112.0  60.0  69.0
3457   100194.0   b'F52'  137.0  85.0  66.0

In [31]:
# Some elements are bytes, change them to strings:
_s["Visit"] = _s["Visit"].apply(lambda x: x.decode("utf-8"))

In [32]:
_s.sample(3)

          MaskID Visit    sbp   dbp    hr
176731  109919.0   F52  174.0  64.0  54.0
142443  107965.0   BLR  140.0  70.0  58.0
28814   101587.0   F08  116.0  75.0  94.0

### Pivot and merge multiple columns:

In [48]:
def pivot_multi_columns(data, targets, index_col, column_col, aggfunc="mean", fill_value=None, dropna=False):
    # Precheck input data:
    assert isinstance(data, pd.DataFrame), TypeError("Input data must be pd.DataFrame.")
    
    # Pre-process input parameters:
    # index_col = [index_col] if not isinstance(index_col, list) else index_col
    
    # Make a placeholder for merging data:
    output = data[[index_col]]
    
    # Loop target columns to aggregate data:
    for ele in targets:
        try:
            tmp_pivot_df = pd.pivot_table(data, values=ele, index=index_col, \
                                          columns=column_col, aggfunc=aggfunc, \
                                          fill_value=fill_value, dropna=dropna).reset_index()
            tmp_pivot_df.columns = [ele + '_' + _col if _col != index_col else _col for _col in tmp_pivot_df.columns.tolist()]
            output = pd.merge(output, tmp_pivot_df, on=index_col, how="left")
        except Exception as e:
            print("Failed in pivot-merging data. Error: {}.".format(e))
            raise
            
    return output

In [49]:
tmp = pivot_multi_columns(_s, targets=["sbp", "dbp", "hr"], index_col="MaskID", column_col="Visit",\
                          aggfunc="mean", fill_value=None, dropna=False)

In [50]:
tmp.sample(3)

,MaskID,sbp_BLR,sbp_EXIT,sbp_F01,sbp_F02,sbp_F03,sbp_F04,sbp_F06,sbp_F08,sbp_F10,sbp_F12,sbp_F14,sbp_F16,sbp_F18,sbp_F20,sbp_F22,sbp_F24,sbp_F26,sbp_F28,sbp_F30,sbp_F32,sbp_F34,sbp_F36,sbp_F38,sbp_F40,sbp_F42,sbp_F44,sbp_F46,sbp_F48,sbp_F50,sbp_F52,sbp_F54,sbp_F56,sbp_F58,sbp_F60,sbp_F62,sbp_F64,sbp_F66,sbp_F68,sbp_F70,sbp_F72,sbp_F74,sbp_F76,sbp_F78,sbp_F80,sbp_F82,sbp_F84,dbp_BLR,dbp_EXIT,dbp_F01,dbp_F02,dbp_F03,dbp_F04,dbp_F06,dbp_F08,dbp_F10,dbp_F12,dbp_F14,dbp_F16,dbp_F18,dbp_F20,dbp_F22,dbp_F24,dbp_F26,dbp_F28,dbp_F30,dbp_F32,dbp_F34,dbp_F36,dbp_F38,dbp_F40,dbp_F42,dbp_F44,dbp_F46,dbp_F48,dbp_F50,dbp_F52,dbp_F54,dbp_F56,dbp_F58,dbp_F60,dbp_F62,dbp_F64,dbp_F66,dbp_F68,dbp_F70,dbp_F72,dbp_F74,dbp_F76,dbp_F78,dbp_F80,dbp_F82,dbp_F84,hr_BLR,hr_EXIT,hr_F01,hr_F02,hr_F03,hr_F04,hr_F06,hr_F08,hr_F10,hr_F12,hr_F14,hr_F16,hr_F18,hr_F20,hr_F22,hr_F24,hr_F26,hr_F28,hr_F30,hr_F32,hr_F34,hr_F36,hr_F38,hr_F40,hr_F42,hr_F44,hr_F46,hr_F48,hr_F50,hr_F52,hr_F54,hr_F56,hr_F58,hr_F60,hr_F62,hr_F64,hr_F66,hr_F68,hr_F70,hr_F72,hr_F74,hr_F76,hr_F78,hr_F80,hr_F82,hr_F84
135903,107603.0,129.0,142.0,NaN,NaN,NaN,127.0,NaN,127.0,NaN,122.0,NaN,155.0,NaN,133.0,NaN,123.0,NaN,145.0,NaN,151.0,NaN,133.0,NaN,144.0,NaN,141.0,NaN,137.0,NaN,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,79.0,NaN,NaN,NaN,72.0,NaN,75.0,NaN,76.0,NaN,93.0,NaN,76.0,NaN,72.0,NaN,82.0,NaN,88.0,NaN,80.0,NaN,86.0,NaN,85.0,NaN,82.0,NaN,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.0,94.0,NaN,NaN,NaN,84.0,NaN,92.0,NaN,94.0,NaN,102.0,NaN,91.0,NaN,91.0,NaN,85.0,NaN,102.0,NaN,92.0,NaN,87.0,NaN,88.0,NaN,97.0,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129266,107224.0,133.0,122.0,123.0,122.0,105.0,137.0,127.0,120.0,NaN,137.0,NaN,129.0,NaN,124.0,NaN,123.0,NaN,112.0,NaN,126.0,NaN,132.0,NaN,128.0,NaN,112.0,NaN,NaN,NaN,149.0,NaN,124.0,NaN,113.0,NaN,135.0,NaN,133.0,NaN,108.0,NaN,122.0,NaN,NaN,NaN,133.0,76.0,86.0,69.0,83.0,55.0,82.0,86.0,71.0,NaN,72.0,NaN,59.0,NaN,69.0,NaN,67.0,NaN,76.0,NaN,65.0,NaN,77.0,NaN,77.0,NaN,72.0,NaN,NaN,NaN,80.0,NaN,61.0,NaN,73.0,NaN,70.0,NaN,83.0,NaN,62.0,NaN,70.0,NaN,NaN,NaN,75.0,75.0,76.0,73.0,79.0,70.0,77.0,81.0,70.0,NaN,55.0,NaN,49.0,NaN,57.0,NaN,65.0,NaN,73.0,NaN,70.0,NaN,64.0,NaN,60.0,NaN,61.0,NaN,NaN,NaN,62.0,NaN,61.0,NaN,60.0,NaN,61.0,NaN,62.0,NaN,61.0,NaN,64.0,NaN,NaN,NaN,64.0
25317,101389.0,139.0,129.0,NaN,NaN,NaN,135.0,NaN,143.0,NaN,153.0,NaN,138.0,NaN,132.0,NaN,122.0,NaN,107.0,NaN,139.0,NaN,139.0,NaN,131.0,NaN,136.0,NaN,124.0,NaN,139.0,NaN,125.0,NaN,119.0,NaN,119.0,NaN,131.0,NaN,135.0,NaN,NaN,NaN,NaN,NaN,NaN,62.0,59.0,NaN,NaN,NaN,68.0,NaN,66.0,NaN,78.0,NaN,69.0,NaN,56.0,NaN,56.0,NaN,48.0,NaN,62.0,NaN,62.0,NaN,55.0,NaN,61.0,NaN,51.0,NaN,65.0,NaN,61.0,NaN,62.0,NaN,61.0,NaN,66.0,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,62.0,61.0,NaN,NaN,NaN,56.0,NaN,59.0,NaN,52.0,NaN,59.0,NaN,73.0,NaN,68.0,NaN,62.0,NaN,64.0,NaN,63.0,NaN,67.0,NaN,65.0,NaN,54.0,NaN,63.0,NaN,61.0,NaN,64.0,NaN,65.0,NaN,61.0,NaN,63.0,NaN,NaN,NaN,NaN,NaN,NaN